WORKER_MIN_SCALER = 20
WORKER_MAX_SCALER = 50
WORKER_CONCURRENCY = (WORKER_MIN_SCALER + WORKER_MAX_SCALER) // 2

DATABASE_AUTO_DELETE_HOUR = 4 + 15  # UTC
DATABASE_AUTO_DELETE_MINUTE = 00
DATABASE_AUTO_DELETE_BEFORE_DAYS = 7
