DEBUG = True
PROFILE = True
MODE = "CCTV"

WORKER_MIN_SCALER = 20
WORKER_MAX_SCALER = 50
WORKER_CONCURRENCY = (WORKER_MIN_SCALER + WORKER_MAX_SCALER) // 2

DATABASE_AUTO_DELETE_HOUR = 4           # UTC To Asia/Seoul
DATABASE_AUTO_DELETE_MINUTE = 00
DATABASE_AUTO_DELETE_DAY_OF_WEEK = 0    # 0: Sunday - 6: Saturday
DATABASE_AUTO_DELETE_BEFORE_DAYS = 7
